### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by helloitsjoe** [helloitsjoe/mbta-client#2]
- [x] Tests
- [x] More complete MBTA API - https://api-v3.mbta.com/docs/swagger/index.html#/
  - [x] Vehicle
  - [x] Trip
  - [x] Stop
  - [x] Shape
  - [x] Service
  - [x] Schedule
  - [x] Route
  - [x] Prediction
  - [x] Alert (see Best Practices https://www.mbta.com/developers/v3-api/best-practices)
  - [x] LiveFacility ?
  - [x] Facility ?
- [x] Docs
- [x] MBTA stop code docs?
- [x] Minified package
- [ ] Selectors
  - [ ] includes attribute selectors
- [x] Map types to strings (see google transit types)
- [x] Helpers
  - [x] `getAllRouteIds()`
  - [x] `getRouteIdByName()`
  - [x] `getAllStopsByRoute()`
  - [x] `getStopByName()`
  - [x] `getFacilityByStop()`
  - [x] `getFacilityIdByName()`
- [ ] TypeScript?
- [x] Remove `timeConstants` in favor of human input
- [ ] Streaming? https://www.mbta.com/developers/v3-api/streaming
- [x] Prediction
  - [x] Ascending/descending sort
  - [x] Include
  - [x] Latitude/Longitude/Radius
  - [x] route_type
